/* Generated By:JavaCC: Do not edit this line. XParserVisitor.java Version 6.0_1 */
package com.brentcroft.util.xpath;

import com.brentcroft.util.xpath.ast.AbbrevForwardStep;
import com.brentcroft.util.xpath.ast.AbbrevReverseStep;
import com.brentcroft.util.xpath.ast.AdditiveExpr;
import com.brentcroft.util.xpath.ast.AndExpr;
import com.brentcroft.util.xpath.ast.AnyKindTest;
import com.brentcroft.util.xpath.ast.AxisStep;
import com.brentcroft.util.xpath.ast.CommentTest;
import com.brentcroft.util.xpath.ast.ContextItemExpr;
import com.brentcroft.util.xpath.ast.DecimalLiteral;
import com.brentcroft.util.xpath.ast.EqualityExpr;
import com.brentcroft.util.xpath.ast.FilterExpr;
import com.brentcroft.util.xpath.ast.ForwardAxis;
import com.brentcroft.util.xpath.ast.FunctionCall;
import com.brentcroft.util.xpath.ast.FunctionQName;
import com.brentcroft.util.xpath.ast.IntegerLiteral;
import com.brentcroft.util.xpath.ast.Minus;
import com.brentcroft.util.xpath.ast.MultiplicativeExpr;
import com.brentcroft.util.xpath.ast.NCName;
import com.brentcroft.util.xpath.ast.NCNameColonStar;
import com.brentcroft.util.xpath.ast.NameTest;
import com.brentcroft.util.xpath.ast.NodeTest;
import com.brentcroft.util.xpath.ast.OrExpr;
import com.brentcroft.util.xpath.ast.PITest;
import com.brentcroft.util.xpath.ast.ParenthesizedExpr;
import com.brentcroft.util.xpath.ast.PathExpr;
import com.brentcroft.util.xpath.ast.Predicate;
import com.brentcroft.util.xpath.ast.PredicateList;
import com.brentcroft.util.xpath.ast.QName;
import com.brentcroft.util.xpath.ast.RelationalExpr;
import com.brentcroft.util.xpath.ast.ReverseAxis;
import com.brentcroft.util.xpath.ast.START;
import com.brentcroft.util.xpath.ast.Slash;
import com.brentcroft.util.xpath.ast.SlashSlash;
import com.brentcroft.util.xpath.ast.StringLiteral;
import com.brentcroft.util.xpath.ast.TextTest;
import com.brentcroft.util.xpath.ast.UnaryExpr;
import com.brentcroft.util.xpath.ast.UnionExpr1;
import com.brentcroft.util.xpath.ast.VarName;
import com.brentcroft.util.xpath.ast.Wildcard;
import com.brentcroft.util.xpath.gob.Gob;
import com.brentcroft.util.xpath.gob.Selection;

public interface XParserVisitor
{
    Selection visit( SimpleNode node, Gob gob, Selection axis );

     Selection visit( START node, Gob gob, Selection axis );

     Selection visit( OrExpr node, Gob gob, Selection axis );

     Selection visit( AndExpr node, Gob gob, Selection axis );

     Selection visit( EqualityExpr node, Gob gob, Selection axis );

     Selection visit( RelationalExpr node, Gob gob, Selection axis );

     Selection visit( AdditiveExpr node, Gob gob, Selection axis );

     Selection visit( MultiplicativeExpr node, Gob gob, Selection axis );

     Selection visit( UnaryExpr node, Gob gob, Selection axis );

     Selection visit( Minus node, Gob gob, Selection axis );

     Selection visit( UnionExpr1 node, Gob gob, Selection axis );

     Selection visit( Slash node, Gob gob, Selection axis );

     Selection visit( SlashSlash node, Gob gob, Selection axis );

     Selection visit( PathExpr node, Gob gob, Selection axis );

     Selection visit( AxisStep node, Gob gob, Selection axis );

     Selection visit( ForwardAxis node, Gob gob, Selection axis );

     Selection visit( AbbrevForwardStep node, Gob gob, Selection axis );

     Selection visit( ReverseAxis node, Gob gob, Selection axis );

     Selection visit( AbbrevReverseStep node, Gob gob, Selection axis );

     Selection visit( NodeTest node, Gob gob, Selection axis );

//     Selection visit( NameTest node, Gob gob, Selection axis );

     Selection visit( Wildcard node, Gob gob, Selection axis );

     Selection visit( NCNameColonStar node, Gob gob, Selection axis );

     Selection visit( FilterExpr node, Gob gob, Selection axis );

    Selection visit( PredicateList node, Gob gob, Selection result );

    Selection visit( Predicate node, Gob gob, Selection axis );

     Selection visit( StringLiteral node, Gob gob, Selection axis );

     Selection visit( IntegerLiteral node, Gob gob, Selection axis );

     Selection visit( DecimalLiteral node, Gob gob, Selection axis );

     Selection visit( VarName node, Gob gob, Selection axis );

     Selection visit( ParenthesizedExpr node, Gob gob, Selection axis );

     Selection visit( ContextItemExpr node, Gob gob, Selection axis );

     Selection visit( FunctionCall node, Gob gob, Selection axis );

     Selection visit( AnyKindTest node, Gob gob, Selection axis );

     Selection visit( TextTest node, Gob gob, Selection axis );

     Selection visit( CommentTest node, Gob gob, Selection axis );

     Selection visit( PITest node, Gob gob, Selection axis );

     Selection visit( NCName node, Gob gob, Selection axis );

     Selection visit( QName node, Gob gob, Selection axis );

     Selection visit( FunctionQName node, Gob gob, Selection axis );
}
/* JavaCC - OriginalChecksum=17aa0418c5383dc7c46648525b66bdc9 (do not edit this line) */
