/* Generated By:JJTree: Do not edit this line. AdditiveExpr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.brentcroft.util.xpath.ast;

import com.brentcroft.util.xpath.gob.Gob;
import com.brentcroft.util.xpath.SimpleNode;
import com.brentcroft.util.xpath.XParser;
import com.brentcroft.util.xpath.XParserVisitor;
import com.brentcroft.util.xpath.gob.Selection;

public
class AdditiveExpr extends SimpleNode
{
  public AdditiveExpr(int id) {
    super(id);
  }

  public AdditiveExpr( XParser p, int id) {
    super(p, id);
  }


  public Selection accept( XParserVisitor visitor, Gob gob, Selection axis )
  {
    return visitor.visit( this, gob, axis );
  }

}
/* JavaCC - OriginalChecksum=a477e31c9c7a28b27da958bb95688aab (do not edit this line) */
